name: ZooImperium
main: es.elzoo.zooimperium.ZooImperium
author: ElZoo
website: https://elzoo.es
version: 1.0.0
depend:
api-version: 1.15
commands:
  zooec:
    description: Abre el enderchest
    usage: "Usage: /zooec"
  dinero:
    description: Devuelve el dinero del jugador
    usage: "Usage: /dinero"